/* eslint-disable @typescript-eslint/no-explicit-any */

import type { Metadata } from 'next'

import './globals.css'

declare global {
  interface Window {
    translation: any
  }
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <meta
        httpEquiv='origin-trial'
        content='Aoeg49e8gXziww8aMaciOT3ocfAg14TCdd6srBr0/ENCVaog72otR4Or4Qjz9qByZNGl2mbK/pxvft9j0jf8sw0AAABReyJvcmlnaW4iOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJmZWF0dXJlIjoiVHJhbnNsYXRpb25BUEkiLCJleHBpcnkiOjE3NTMxNDI0MDB9'
      />
      <body className={`antialiased`}>{children}</body>
    </html>
  )
}
